2024-11-19 10:30:38,857 - src.currency_exchange.app.app_server - INFO - --- APP started
2024-11-19 10:31:07,760 - fastapi_cache.decorator - WARNING - Error retrieving cache key 'fastapi-cache::58a57c680548a569aad222de57d7805e' from backend:
Traceback (most recent call last):
  File "E:\Prog\projects\python-projects\Zhukov_roadmap\currency_exchange\.venv\Lib\site-packages\redis\asyncio\connection.py", line 782, in read_response
    response = await self._parser.read_response(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Prog\projects\python-projects\Zhukov_roadmap\currency_exchange\.venv\Lib\site-packages\redis\asyncio\connection.py", line 411, in read_response
    await self.read_from_socket()
  File "E:\Prog\projects\python-projects\Zhukov_roadmap\currency_exchange\.venv\Lib\site-packages\redis\asyncio\connection.py", line 392, in read_from_socket
    buffer = await self._stream.read(self._read_size)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Prog\Programs\python\python3_12_3\Lib\asyncio\streams.py", line 713, in read
    await self._wait_for_data('read')
  File "E:\Prog\Programs\python\python3_12_3\Lib\asyncio\streams.py", line 545, in _wait_for_data
    await self._waiter
  File "E:\Prog\Programs\python\python3_12_3\Lib\asyncio\selector_events.py", line 1013, in _read_ready__data_received
    data = self._sock.recv(self.max_size)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [WinError 10054] Удаленный хост принудительно разорвал существующее подключение

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Prog\projects\python-projects\Zhukov_roadmap\currency_exchange\.venv\Lib\site-packages\fastapi_cache\decorator.py", line 178, in inner
    ttl, cached = await backend.get_with_ttl(cache_key)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Prog\projects\python-projects\Zhukov_roadmap\currency_exchange\.venv\Lib\site-packages\fastapi_cache\backends\redis.py", line 16, in get_with_ttl
    return await pipe.ttl(key).get(key).execute()  # type: ignore[union-attr,no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Prog\projects\python-projects\Zhukov_roadmap\currency_exchange\.venv\Lib\site-packages\redis\asyncio\client.py", line 1399, in execute
    return await conn.retry.call_with_retry(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Prog\projects\python-projects\Zhukov_roadmap\currency_exchange\.venv\Lib\site-packages\redis\asyncio\retry.py", line 62, in call_with_retry
    await fail(error)
  File "E:\Prog\projects\python-projects\Zhukov_roadmap\currency_exchange\.venv\Lib\site-packages\redis\asyncio\retry.py", line 59, in call_with_retry
    return await do()
           ^^^^^^^^^^
  File "E:\Prog\projects\python-projects\Zhukov_roadmap\currency_exchange\.venv\Lib\site-packages\redis\asyncio\client.py", line 1245, in _execute_transaction
    await self.parse_response(connection, "_")
  File "E:\Prog\projects\python-projects\Zhukov_roadmap\currency_exchange\.venv\Lib\site-packages\redis\asyncio\client.py", line 1338, in parse_response
    result = await super().parse_response(connection, command_name, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Prog\projects\python-projects\Zhukov_roadmap\currency_exchange\.venv\Lib\site-packages\redis\asyncio\client.py", line 539, in parse_response
    response = await connection.read_response()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Prog\projects\python-projects\Zhukov_roadmap\currency_exchange\.venv\Lib\site-packages\redis\asyncio\connection.py", line 796, in read_response
    raise ConnectionError(f"Error while reading from {host_error} : {e.args}")
redis.exceptions.ConnectionError: Error while reading from 127.0.0.1:6379 : (10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None)
2024-11-19 10:31:26,495 - src.currency_exchange.app.app_server - INFO - --- APP down
2024-11-19 10:36:31,991 - src.currency_exchange.app.app_server - INFO - --- APP started
2024-11-19 10:36:38,206 - fastapi_cache.decorator - WARNING - Error retrieving cache key 'fastapi-cache::9c2f5b0aa73af375d14e1c46187fa7c8' from backend:
Traceback (most recent call last):
  File "E:\Prog\projects\python-projects\Zhukov_roadmap\currency_exchange\.venv\Lib\site-packages\redis\asyncio\connection.py", line 577, in connect
    await self.retry.call_with_retry(
  File "E:\Prog\projects\python-projects\Zhukov_roadmap\currency_exchange\.venv\Lib\site-packages\redis\asyncio\retry.py", line 59, in call_with_retry
    return await do()
           ^^^^^^^^^^
  File "E:\Prog\projects\python-projects\Zhukov_roadmap\currency_exchange\.venv\Lib\site-packages\redis\asyncio\connection.py", line 922, in _connect
    reader, writer = await asyncio.open_connection(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Prog\Programs\python\python3_12_3\Lib\asyncio\streams.py", line 48, in open_connection
    transport, _ = await loop.create_connection(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Prog\Programs\python\python3_12_3\Lib\asyncio\base_events.py", line 1122, in create_connection
    raise exceptions[0]
  File "E:\Prog\Programs\python\python3_12_3\Lib\asyncio\base_events.py", line 1104, in create_connection
    sock = await self._connect_sock(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Prog\Programs\python\python3_12_3\Lib\asyncio\base_events.py", line 1007, in _connect_sock
    await self.sock_connect(sock, address)
  File "E:\Prog\Programs\python\python3_12_3\Lib\asyncio\selector_events.py", line 651, in sock_connect
    return await fut
           ^^^^^^^^^
  File "E:\Prog\Programs\python\python3_12_3\Lib\asyncio\selector_events.py", line 691, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('127.0.0.1', 6379)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Prog\projects\python-projects\Zhukov_roadmap\currency_exchange\.venv\Lib\site-packages\fastapi_cache\decorator.py", line 178, in inner
    ttl, cached = await backend.get_with_ttl(cache_key)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Prog\projects\python-projects\Zhukov_roadmap\currency_exchange\.venv\Lib\site-packages\fastapi_cache\backends\redis.py", line 16, in get_with_ttl
    return await pipe.ttl(key).get(key).execute()  # type: ignore[union-attr,no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Prog\projects\python-projects\Zhukov_roadmap\currency_exchange\.venv\Lib\site-packages\redis\asyncio\client.py", line 1392, in execute
    conn = await self.connection_pool.get_connection("MULTI", self.shard_hint)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Prog\projects\python-projects\Zhukov_roadmap\currency_exchange\.venv\Lib\site-packages\redis\asyncio\connection.py", line 1375, in get_connection
    await connection.connect()
  File "E:\Prog\projects\python-projects\Zhukov_roadmap\currency_exchange\.venv\Lib\site-packages\redis\asyncio\connection.py", line 585, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 10061 connecting to 127.0.0.1:6379. 10061.
2024-11-19 10:36:40,333 - fastapi_cache.decorator - WARNING - Error setting cache key 'fastapi-cache::9c2f5b0aa73af375d14e1c46187fa7c8' in backend:
Traceback (most recent call last):
  File "E:\Prog\projects\python-projects\Zhukov_roadmap\currency_exchange\.venv\Lib\site-packages\redis\asyncio\connection.py", line 577, in connect
    await self.retry.call_with_retry(
  File "E:\Prog\projects\python-projects\Zhukov_roadmap\currency_exchange\.venv\Lib\site-packages\redis\asyncio\retry.py", line 59, in call_with_retry
    return await do()
           ^^^^^^^^^^
  File "E:\Prog\projects\python-projects\Zhukov_roadmap\currency_exchange\.venv\Lib\site-packages\redis\asyncio\connection.py", line 922, in _connect
    reader, writer = await asyncio.open_connection(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Prog\Programs\python\python3_12_3\Lib\asyncio\streams.py", line 48, in open_connection
    transport, _ = await loop.create_connection(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Prog\Programs\python\python3_12_3\Lib\asyncio\base_events.py", line 1122, in create_connection
    raise exceptions[0]
  File "E:\Prog\Programs\python\python3_12_3\Lib\asyncio\base_events.py", line 1104, in create_connection
    sock = await self._connect_sock(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Prog\Programs\python\python3_12_3\Lib\asyncio\base_events.py", line 1007, in _connect_sock
    await self.sock_connect(sock, address)
  File "E:\Prog\Programs\python\python3_12_3\Lib\asyncio\selector_events.py", line 651, in sock_connect
    return await fut
           ^^^^^^^^^
  File "E:\Prog\Programs\python\python3_12_3\Lib\asyncio\selector_events.py", line 691, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('127.0.0.1', 6379)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Prog\projects\python-projects\Zhukov_roadmap\currency_exchange\.venv\Lib\site-packages\fastapi_cache\decorator.py", line 191, in inner
    await backend.set(cache_key, to_cache, expire)
  File "E:\Prog\projects\python-projects\Zhukov_roadmap\currency_exchange\.venv\Lib\site-packages\fastapi_cache\backends\redis.py", line 22, in set
    await self.redis.set(key, value, ex=expire)  # type: ignore[union-attr]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Prog\projects\python-projects\Zhukov_roadmap\currency_exchange\.venv\Lib\site-packages\redis\asyncio\client.py", line 513, in execute_command
    conn = self.connection or await pool.get_connection(command_name, **options)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Prog\projects\python-projects\Zhukov_roadmap\currency_exchange\.venv\Lib\site-packages\redis\asyncio\connection.py", line 1375, in get_connection
    await connection.connect()
  File "E:\Prog\projects\python-projects\Zhukov_roadmap\currency_exchange\.venv\Lib\site-packages\redis\asyncio\connection.py", line 585, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 10061 connecting to 127.0.0.1:6379. 10061.
2024-11-19 10:38:13,080 - src.currency_exchange.app.app_server - INFO - --- APP down
2024-11-19 10:38:17,710 - src.currency_exchange.app.app_server - INFO - --- APP started
2024-11-19 10:38:32,844 - fastapi_cache.decorator - WARNING - Error retrieving cache key 'fastapi-cache::d95226f76ae8ffa58a5e7f521017d233' from backend:
Traceback (most recent call last):
  File "E:\Prog\projects\python-projects\Zhukov_roadmap\currency_exchange\.venv\Lib\site-packages\redis\asyncio\connection.py", line 577, in connect
    await self.retry.call_with_retry(
  File "E:\Prog\projects\python-projects\Zhukov_roadmap\currency_exchange\.venv\Lib\site-packages\redis\asyncio\retry.py", line 59, in call_with_retry
    return await do()
           ^^^^^^^^^^
  File "E:\Prog\projects\python-projects\Zhukov_roadmap\currency_exchange\.venv\Lib\site-packages\redis\asyncio\connection.py", line 922, in _connect
    reader, writer = await asyncio.open_connection(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Prog\Programs\python\python3_12_3\Lib\asyncio\streams.py", line 48, in open_connection
    transport, _ = await loop.create_connection(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Prog\Programs\python\python3_12_3\Lib\asyncio\base_events.py", line 1122, in create_connection
    raise exceptions[0]
  File "E:\Prog\Programs\python\python3_12_3\Lib\asyncio\base_events.py", line 1104, in create_connection
    sock = await self._connect_sock(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Prog\Programs\python\python3_12_3\Lib\asyncio\base_events.py", line 1007, in _connect_sock
    await self.sock_connect(sock, address)
  File "E:\Prog\Programs\python\python3_12_3\Lib\asyncio\selector_events.py", line 651, in sock_connect
    return await fut
           ^^^^^^^^^
  File "E:\Prog\Programs\python\python3_12_3\Lib\asyncio\selector_events.py", line 691, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('127.0.0.1', 6379)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Prog\projects\python-projects\Zhukov_roadmap\currency_exchange\.venv\Lib\site-packages\fastapi_cache\decorator.py", line 178, in inner
    ttl, cached = await backend.get_with_ttl(cache_key)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Prog\projects\python-projects\Zhukov_roadmap\currency_exchange\.venv\Lib\site-packages\fastapi_cache\backends\redis.py", line 16, in get_with_ttl
    return await pipe.ttl(key).get(key).execute()  # type: ignore[union-attr,no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Prog\projects\python-projects\Zhukov_roadmap\currency_exchange\.venv\Lib\site-packages\redis\asyncio\client.py", line 1392, in execute
    conn = await self.connection_pool.get_connection("MULTI", self.shard_hint)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Prog\projects\python-projects\Zhukov_roadmap\currency_exchange\.venv\Lib\site-packages\redis\asyncio\connection.py", line 1375, in get_connection
    await connection.connect()
  File "E:\Prog\projects\python-projects\Zhukov_roadmap\currency_exchange\.venv\Lib\site-packages\redis\asyncio\connection.py", line 585, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 10061 connecting to 127.0.0.1:6379. 10061.
2024-11-19 10:38:34,959 - fastapi_cache.decorator - WARNING - Error setting cache key 'fastapi-cache::d95226f76ae8ffa58a5e7f521017d233' in backend:
Traceback (most recent call last):
  File "E:\Prog\projects\python-projects\Zhukov_roadmap\currency_exchange\.venv\Lib\site-packages\redis\asyncio\connection.py", line 577, in connect
    await self.retry.call_with_retry(
  File "E:\Prog\projects\python-projects\Zhukov_roadmap\currency_exchange\.venv\Lib\site-packages\redis\asyncio\retry.py", line 59, in call_with_retry
    return await do()
           ^^^^^^^^^^
  File "E:\Prog\projects\python-projects\Zhukov_roadmap\currency_exchange\.venv\Lib\site-packages\redis\asyncio\connection.py", line 922, in _connect
    reader, writer = await asyncio.open_connection(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Prog\Programs\python\python3_12_3\Lib\asyncio\streams.py", line 48, in open_connection
    transport, _ = await loop.create_connection(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Prog\Programs\python\python3_12_3\Lib\asyncio\base_events.py", line 1122, in create_connection
    raise exceptions[0]
  File "E:\Prog\Programs\python\python3_12_3\Lib\asyncio\base_events.py", line 1104, in create_connection
    sock = await self._connect_sock(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Prog\Programs\python\python3_12_3\Lib\asyncio\base_events.py", line 1007, in _connect_sock
    await self.sock_connect(sock, address)
  File "E:\Prog\Programs\python\python3_12_3\Lib\asyncio\selector_events.py", line 651, in sock_connect
    return await fut
           ^^^^^^^^^
  File "E:\Prog\Programs\python\python3_12_3\Lib\asyncio\selector_events.py", line 691, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('127.0.0.1', 6379)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Prog\projects\python-projects\Zhukov_roadmap\currency_exchange\.venv\Lib\site-packages\fastapi_cache\decorator.py", line 191, in inner
    await backend.set(cache_key, to_cache, expire)
  File "E:\Prog\projects\python-projects\Zhukov_roadmap\currency_exchange\.venv\Lib\site-packages\fastapi_cache\backends\redis.py", line 22, in set
    await self.redis.set(key, value, ex=expire)  # type: ignore[union-attr]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Prog\projects\python-projects\Zhukov_roadmap\currency_exchange\.venv\Lib\site-packages\redis\asyncio\client.py", line 513, in execute_command
    conn = self.connection or await pool.get_connection(command_name, **options)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Prog\projects\python-projects\Zhukov_roadmap\currency_exchange\.venv\Lib\site-packages\redis\asyncio\connection.py", line 1375, in get_connection
    await connection.connect()
  File "E:\Prog\projects\python-projects\Zhukov_roadmap\currency_exchange\.venv\Lib\site-packages\redis\asyncio\connection.py", line 585, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 10061 connecting to 127.0.0.1:6379. 10061.
2024-11-19 10:39:06,588 - src.currency_exchange.app.app_server - INFO - --- APP down
2024-11-19 10:39:12,093 - src.currency_exchange.app.app_server - INFO - --- APP started
2024-11-19 10:39:43,164 - src.currency_exchange.app.app_server - INFO - --- APP down
2024-11-19 10:39:44,530 - src.currency_exchange.app.app_server - INFO - --- APP started
2024-11-19 10:41:05,246 - src.currency_exchange.app.app_server - INFO - --- APP down
2024-11-19 10:41:06,159 - src.currency_exchange.app.app_server - INFO - --- APP started
2024-11-19 10:41:28,811 - src.currency_exchange.app.app_server - INFO - --- APP down
2024-11-19 10:41:29,715 - src.currency_exchange.app.app_server - INFO - --- APP started
2024-11-19 10:41:44,723 - src.currency_exchange.app.app_server - INFO - --- APP down
2024-11-19 10:41:45,597 - src.currency_exchange.app.app_server - INFO - --- APP started
2024-11-19 10:42:27,943 - src.currency_exchange.app.app_server - INFO - --- APP down
2024-11-19 10:42:29,108 - src.currency_exchange.app.app_server - INFO - --- APP started
2024-11-19 10:43:22,245 - src.currency_exchange.app.app_server - INFO - --- APP down
2024-11-19 10:43:23,364 - src.currency_exchange.app.app_server - INFO - --- APP started
2024-11-19 10:46:18,576 - src.currency_exchange.app.app_server - INFO - --- APP down
2024-11-19 10:46:19,791 - src.currency_exchange.app.app_server - INFO - --- APP started
2024-11-19 10:48:04,442 - src.currency_exchange.app.app_server - INFO - --- APP down
2024-11-19 10:48:05,633 - src.currency_exchange.app.app_server - INFO - --- APP started
2024-11-19 10:50:04,462 - src.currency_exchange.app.app_server - INFO - --- APP down
2024-11-19 10:50:05,683 - src.currency_exchange.app.app_server - INFO - --- APP started
2024-11-19 10:50:26,956 - src.currency_exchange.app.app_server - INFO - --- APP down
2024-11-19 10:50:59,576 - src.currency_exchange.app.app_server - INFO - --- APP started
2024-11-19 10:52:34,290 - src.currency_exchange.app.app_server - INFO - --- APP down
2024-11-19 10:52:35,481 - src.currency_exchange.app.app_server - INFO - --- APP started
2024-11-19 10:52:53,638 - src.currency_exchange.app.app_server - INFO - --- APP down
2024-11-19 10:52:54,861 - src.currency_exchange.app.app_server - INFO - --- APP started
2024-11-19 10:55:42,957 - src.currency_exchange.app.app_server - INFO - --- APP down
2024-11-19 10:56:39,131 - src.currency_exchange.app.app_server - INFO - --- APP started
2024-11-19 10:56:42,160 - src.currency_exchange.app.app_server - INFO - --- APP down
2024-11-19 11:05:23,371 - src.currency_exchange.app.app_server - INFO - --- APP started
2024-11-19 11:06:09,888 - src.currency_exchange.app.app_server - INFO - --- APP down
2024-11-19 11:06:10,928 - src.currency_exchange.app.app_server - INFO - --- APP started
2024-11-19 11:06:34,359 - src.currency_exchange.app.app_server - INFO - --- APP down
2024-11-19 11:11:31,196 - src.currency_exchange.app.app_server - INFO - --- APP started
2024-11-19 11:12:19,485 - src.currency_exchange.app.app_server - INFO - --- APP down
2024-11-19 11:12:20,785 - src.currency_exchange.app.app_server - INFO - --- APP started
2024-11-19 11:14:06,395 - src.currency_exchange.app.app_server - INFO - --- APP down
2024-11-19 11:14:07,749 - src.currency_exchange.app.app_server - INFO - --- APP started
2024-11-19 11:14:25,183 - src.currency_exchange.app.app_server - INFO - --- APP down
2024-11-19 11:14:26,304 - src.currency_exchange.app.app_server - INFO - --- APP started
2024-11-19 11:21:24,388 - src.currency_exchange.app.app_server - INFO - --- APP down
2024-11-19 11:21:25,606 - src.currency_exchange.app.app_server - INFO - --- APP started
2024-11-19 11:22:59,379 - src.currency_exchange.app.app_server - INFO - --- APP down
2024-11-19 11:23:00,518 - src.currency_exchange.app.app_server - INFO - --- APP started
2024-11-19 11:23:10,678 - src.currency_exchange.app.app_server - INFO - --- APP down
2024-11-19 11:23:11,885 - src.currency_exchange.app.app_server - INFO - --- APP started
2024-11-19 11:23:38,865 - src.currency_exchange.app.app_server - INFO - --- APP down
2024-11-19 11:23:39,916 - src.currency_exchange.app.app_server - INFO - --- APP started
2024-11-19 11:24:18,335 - src.currency_exchange.app.app_server - INFO - --- APP down
2024-11-19 11:24:19,632 - src.currency_exchange.app.app_server - INFO - --- APP started
2024-11-19 11:26:39,375 - src.currency_exchange.app.app_server - INFO - --- APP down
2024-11-19 11:26:40,706 - src.currency_exchange.app.app_server - INFO - --- APP started
2024-11-19 11:27:12,936 - src.currency_exchange.app.app_server - INFO - --- APP down
2024-11-19 11:27:14,026 - src.currency_exchange.app.app_server - INFO - --- APP started
2024-11-19 11:28:02,366 - src.currency_exchange.app.app_server - INFO - --- APP down
2024-11-19 11:28:03,456 - src.currency_exchange.app.app_server - INFO - --- APP started
2024-11-19 11:32:04,937 - src.currency_exchange.app.app_server - INFO - --- APP down
2024-11-19 11:32:06,165 - src.currency_exchange.app.app_server - INFO - --- APP started
2024-11-19 11:33:05,240 - src.currency_exchange.app.app_server - INFO - --- APP down
2024-11-19 11:33:06,256 - src.currency_exchange.app.app_server - INFO - --- APP started
2024-11-19 11:33:06,578 - src.currency_exchange.app.app_server - INFO - --- APP down
2024-11-19 11:33:07,532 - src.currency_exchange.app.app_server - INFO - --- APP started
2024-11-19 11:33:36,727 - src.currency_exchange.app.app_server - INFO - --- APP down
2024-11-19 11:33:37,906 - src.currency_exchange.app.app_server - INFO - --- APP started
2024-11-19 11:33:58,348 - src.currency_exchange.app.app_server - INFO - --- APP down
2024-11-19 11:41:29,148 - src.currency_exchange.app.app_server - INFO - --- APP started
2024-11-19 11:43:03,798 - src.currency_exchange.app.app_server - INFO - --- APP down
2024-11-19 11:43:04,942 - src.currency_exchange.app.app_server - INFO - --- APP started
2024-11-19 11:44:36,475 - src.currency_exchange.app.app_server - INFO - --- APP down
2024-11-19 11:44:37,739 - src.currency_exchange.app.app_server - INFO - --- APP started
2024-11-19 11:45:01,573 - src.currency_exchange.app.app_server - INFO - --- APP down
2024-11-19 11:45:02,854 - src.currency_exchange.app.app_server - INFO - --- APP started
2024-11-19 11:45:39,356 - src.currency_exchange.app.app_server - INFO - --- APP down
2024-11-19 11:45:40,531 - src.currency_exchange.app.app_server - INFO - --- APP started
2024-11-19 11:46:03,481 - src.currency_exchange.app.app_server - INFO - --- APP down
2024-11-19 11:46:04,639 - src.currency_exchange.app.app_server - INFO - --- APP started
2024-11-19 11:46:12,087 - src.currency_exchange.app.app_server - INFO - --- APP down
2024-11-19 11:46:13,246 - src.currency_exchange.app.app_server - INFO - --- APP started
2024-11-19 11:55:34,022 - src.currency_exchange.app.app_server - INFO - --- APP down
2024-11-19 12:06:47,417 - src.currency_exchange.app.app_server - INFO - --- APP started
2024-11-19 12:18:50,678 - src.currency_exchange.app.app_server - INFO - --- APP down
2024-11-19 12:18:52,606 - src.currency_exchange.app.app_server - INFO - --- APP started
2024-11-19 12:23:52,901 - src.currency_exchange.app.app_server - INFO - --- APP down
2024-11-19 12:23:53,834 - src.currency_exchange.app.app_server - INFO - --- APP started
2024-11-19 12:26:53,078 - src.currency_exchange.app.app_server - INFO - --- APP down
2024-11-19 12:26:53,953 - src.currency_exchange.app.app_server - INFO - --- APP started
2024-11-19 12:27:20,516 - src.currency_exchange.app.app_server - INFO - --- APP down
2024-11-19 12:27:21,529 - src.currency_exchange.app.app_server - INFO - --- APP started
2024-11-19 12:27:33,450 - src.currency_exchange.app.app_server - INFO - --- APP down
2024-11-19 12:27:34,479 - src.currency_exchange.app.app_server - INFO - --- APP started
2024-11-19 12:28:11,504 - src.currency_exchange.app.app_server - INFO - --- APP down
2024-11-19 12:28:12,564 - src.currency_exchange.app.app_server - INFO - --- APP started
2024-11-19 12:28:36,461 - src.currency_exchange.app.app_server - INFO - --- APP down
2024-11-19 12:30:11,753 - src.currency_exchange.app.app_server - INFO - --- APP started
2024-11-19 12:30:57,481 - src.currency_exchange.app.app_server - INFO - --- APP down
2024-11-19 12:30:58,465 - src.currency_exchange.app.app_server - INFO - --- APP started
2024-11-19 12:31:25,897 - src.currency_exchange.app.app_server - INFO - --- APP down
2024-11-19 12:31:26,691 - src.currency_exchange.app.app_server - INFO - --- APP started
2024-11-19 12:32:49,165 - src.currency_exchange.app.app_server - INFO - --- APP down
2024-11-19 12:32:50,047 - src.currency_exchange.app.app_server - INFO - --- APP started
2024-11-19 12:33:58,945 - src.currency_exchange.app.app_server - INFO - --- APP down
2024-11-19 12:33:59,860 - src.currency_exchange.app.app_server - INFO - --- APP started
2024-11-19 12:34:05,984 - src.currency_exchange.app.app_server - INFO - --- APP down
2024-11-19 12:34:06,970 - src.currency_exchange.app.app_server - INFO - --- APP started
2024-11-19 12:36:35,826 - src.currency_exchange.app.app_server - INFO - --- APP down
2024-11-19 12:36:36,893 - src.currency_exchange.app.app_server - INFO - --- APP started
2024-11-19 12:37:01,052 - src.currency_exchange.app.app_server - INFO - --- APP down
2024-11-19 12:37:01,903 - src.currency_exchange.app.app_server - INFO - --- APP started
2024-11-19 12:39:37,172 - src.currency_exchange.app.app_server - INFO - --- APP down
2024-11-19 12:39:38,067 - src.currency_exchange.app.app_server - INFO - --- APP started
2024-11-19 12:39:42,437 - src.currency_exchange.app.app_server - INFO - --- APP down
2024-11-19 12:39:43,334 - src.currency_exchange.app.app_server - INFO - --- APP started
2024-11-19 12:42:04,091 - src.currency_exchange.app.app_server - INFO - --- APP down
2024-11-19 12:42:05,075 - src.currency_exchange.app.app_server - INFO - --- APP started
2024-11-19 12:42:34,427 - src.currency_exchange.app.app_server - INFO - --- APP down
2024-11-19 12:42:35,478 - src.currency_exchange.app.app_server - INFO - --- APP started
2024-11-19 12:42:37,710 - src.currency_exchange.app.app_server - INFO - --- APP down
2024-11-19 12:42:38,594 - src.currency_exchange.app.app_server - INFO - --- APP started
2024-11-19 12:42:48,509 - src.currency_exchange.app.app_server - INFO - --- APP down
2024-11-19 12:42:49,594 - src.currency_exchange.app.app_server - INFO - --- APP started
2024-11-19 12:44:17,083 - src.currency_exchange.app.app_server - INFO - --- APP down
2024-11-19 12:44:18,169 - src.currency_exchange.app.app_server - INFO - --- APP started
2024-11-19 12:44:42,998 - src.currency_exchange.app.app_server - INFO - --- APP down
2024-11-19 12:44:43,904 - src.currency_exchange.app.app_server - INFO - --- APP started
2024-11-19 12:44:54,832 - src.currency_exchange.app.app_server - INFO - --- APP down
2024-11-19 12:44:55,633 - src.currency_exchange.app.app_server - INFO - --- APP started
2024-11-19 12:45:52,552 - src.currency_exchange.app.app_server - INFO - --- APP down
2024-11-19 12:45:53,504 - src.currency_exchange.app.app_server - INFO - --- APP started
2024-11-19 12:48:21,993 - src.currency_exchange.app.app_server - INFO - --- APP down
2024-11-19 12:48:22,912 - src.currency_exchange.app.app_server - INFO - --- APP started
2024-11-19 12:48:42,062 - src.currency_exchange.app.app_server - INFO - --- APP down
2024-11-19 12:48:42,829 - src.currency_exchange.app.app_server - INFO - --- APP started
2024-11-19 12:48:52,792 - src.currency_exchange.app.app_server - INFO - --- APP down
2024-11-19 12:48:53,704 - src.currency_exchange.app.app_server - INFO - --- APP started
2024-11-19 12:50:17,854 - src.currency_exchange.app.app_server - INFO - --- APP down
2024-11-19 12:50:18,734 - src.currency_exchange.app.app_server - INFO - --- APP started
2024-11-19 12:50:33,918 - src.currency_exchange.app.app_server - INFO - --- APP down
2024-11-19 12:50:34,935 - src.currency_exchange.app.app_server - INFO - --- APP started
2024-11-19 12:50:36,100 - src.currency_exchange.app.app_server - INFO - --- APP down
2024-11-19 12:51:15,597 - src.currency_exchange.app.app_server - INFO - --- APP started
2024-11-19 12:51:27,503 - src.currency_exchange.app.app_server - INFO - --- APP down
2024-11-19 12:52:30,274 - src.currency_exchange.app.app_server - INFO - --- APP started
2024-11-19 12:54:54,333 - src.currency_exchange.app.app_server - INFO - --- APP down
2024-11-19 12:55:24,184 - src.currency_exchange.app.app_server - INFO - --- APP started
2024-11-19 12:55:46,054 - src.currency_exchange.app.app_server - INFO - --- APP down
2024-11-19 12:55:47,018 - src.currency_exchange.app.app_server - INFO - --- APP started
2024-11-19 13:03:20,443 - src.currency_exchange.app.app_server - INFO - --- APP down
2024-11-19 13:30:41,839 - src.currency_exchange.app.app_server - INFO - --- APP started
2024-11-19 13:32:31,454 - src.currency_exchange.app.app_server - INFO - --- APP started
2024-11-19 13:35:33,804 - src.currency_exchange.app.app_server - INFO - --- APP started
2024-11-19 13:39:50,584 - src.currency_exchange.app.app_server - INFO - --- APP started
2024-11-19 13:47:48,983 - src.currency_exchange.app.app_server - INFO - --- APP started
2024-11-19 13:49:32,496 - src.currency_exchange.app.app_server - INFO - --- APP started
2024-11-19 13:51:35,236 - src.currency_exchange.app.app_server - INFO - --- APP started
2024-11-19 13:52:18,992 - src.currency_exchange.app.app_server - INFO - --- APP started
2024-11-19 13:58:33,418 - src.currency_exchange.app.app_server - INFO - --- APP started
2024-11-19 13:58:34,509 - src.currency_exchange.app.app_server - INFO - --- APP down
2024-11-19 13:58:39,351 - src.currency_exchange.app.app_server - INFO - --- APP started
2024-11-19 14:01:20,863 - src.currency_exchange.app.app_server - INFO - --- APP started
2024-11-19 15:32:32,666 - src.currency_exchange.app.app_server - INFO - --- APP started
2024-11-19 15:32:34,597 - src.currency_exchange.app.app_server - INFO - --- APP down
2024-11-19 15:32:39,385 - src.currency_exchange.app.app_server - INFO - --- APP started
2024-11-19 15:35:03,437 - src.currency_exchange.app.app_server - INFO - --- APP started
2024-11-19 15:37:30,716 - src.currency_exchange.app.app_server - INFO - --- APP started
2024-11-19 15:37:58,569 - src.currency_exchange.app.app_server - INFO - --- APP down
2024-11-19 15:38:23,686 - src.currency_exchange.app.app_server - INFO - --- APP started
2024-11-19 15:38:33,201 - src.currency_exchange.app.app_server - INFO - --- APP down
2024-11-19 15:38:34,399 - src.currency_exchange.app.app_server - INFO - --- APP started
2024-11-19 15:40:06,723 - src.currency_exchange.app.app_server - INFO - --- APP down
2024-11-19 15:40:08,025 - src.currency_exchange.app.app_server - INFO - --- APP started
2024-11-19 15:43:17,845 - src.currency_exchange.app.app_server - INFO - --- APP started
2024-11-19 15:43:19,134 - src.currency_exchange.app.app_server - INFO - --- APP down
2024-11-19 15:43:23,620 - src.currency_exchange.app.app_server - INFO - --- APP started
2024-11-19 16:04:11,149 - src.currency_exchange.app.app_server - INFO - --- APP started
